### ISSUE TITLE
how to use in angular

### ISSUE THREAD

**Issue by alanhe421** [smbolton/dagre-d3v4#2]
I want to use it in angular app.

**Comment by theabolton** [comment]
Yes, I bet you could do some cool stuff with AngularJS, D3, and Dagre! Unfortunately, I don't have any resources on doing so, but a quick Google search turns up some leads, such as [this stackoverflow question](https://stackoverflow.com/questions/23469442/integrating-angularjs-and-dagred3-angularjs-directive-does-not-update-on-model). Good luck!
