### ISSUE TITLE
The order of the same layer nodes

### ISSUE THREAD

**Issue by wopicoun** [smbolton/dagre-d3v4#3]
How does dagre determine the order (left,right side) of nodes?
If I want graph to follow the order of my add node sequence, how can I do ?

when I add node by ABCD, it work well, but when map becomes more complicated. it wrong.

e.g.  A.B1.C1.D1.E1.F1
![error](https://user-images.githubusercontent.com/32476905/31341441-0d10a682-ad3c-11e7-8d7b-7586bc9de98e.png)

Thanks a lot. It it a very wonderful tool.

**Comment by theabolton** [comment]
Are you asking how to get B1, C1, and D1 to appear in order, left to right, in the layout?

If so, then the answer is, I don't believe you can at this time. Dagre is a tool for *automatically laying out complex graphs*, and doesn't provide that sort of low-level placement control. See the dagre wiki section on [Configuring the Layout](https://github.com/cpettitt/dagre/wiki#configuring-the-layout) for information on what you can control. Note that if you already know the desired rank and order of your nodes, you don't need a layout algorithm like dagre, you can create your layout manually (perhaps with the help of one of the many graph utility libraries for D3).

Hope that helps–let me know if I understood your question correctly.

**Comment by wopicoun** [comment]
Yes, this has solved my question. Maybe I should try D3's native way to draw.

Finally, thank you very much for this reply.
